/*
 * Copyright (C) 2010-2018 Gordon Fraser, Andrea Arcuri and EvoSuite
 * contributors
 *
 * Copyright (C) 2021- SmartUt contributors
 *
 * SmartUt is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3.0 of the License, or
 * (at your option) any later version.
 *
 * SmartUt is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with SmartUt. If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * This file was automatically generated by SmartUt
 */

package com.examples.with.different.packagename.testcarver;

import org.junit.Test;
//import org.junit.runner.RunWith;
//import org.smartut.junit.SmartUtRunner;
import static org.junit.Assert.*;
import com.examples.with.different.packagename.testcarver.Person;

//@RunWith(SmartUtRunner.class)
public class TestPerson {

//	@BeforeClass 
//	public static void initSmartUtFramework(){ 
//		org.smartut.Properties.REPLACE_CALLS = true;
//	} 



	@Test
	public void test0_1() throws Throwable {
		Person person0 = new Person("", "");
		String string0 = person0.getFirstName();
		assertEquals("", string0);
	}



	@Test
	public void test0() throws Throwable {
		Person person0 = new Person("", "");
		String string0 = person0.getLastName();
		assertEquals("", string0);
	}


}
