/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by SmartUt
 * Mon Jun 29 13:23:52 GMT 2020
 */

package org.ant_project_example;

import org.smartut.runtime.annotation.SmartUtClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.smartut.runtime.sandbox.Sandbox;
import org.smartut.runtime.sandbox.Sandbox.SandboxMode;

@SmartUtClassExclude
public class CharacterCounter_ESTest_scaffolding {

  @org.junit.Rule 
  public org.smartut.runtime.vnet.NonFunctionalRequirementRule nfr = new org.smartut.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.smartut.runtime.thread.ThreadStopper threadStopper =  new org.smartut.runtime.thread.ThreadStopper (org.smartut.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initSmartUtFramework() { 
    org.smartut.runtime.RuntimeSettings.className = "org.ant_project_example.CharacterCounter";
    org.smartut.runtime.GuiSupport.initialize();
    org.smartut.runtime.RuntimeSettings.maxNumberOfThreads = 100;
    org.smartut.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000;
    org.smartut.runtime.RuntimeSettings.mockSystemIn = true;
    org.smartut.runtime.RuntimeSettings.sandboxMode = org.smartut.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED;
    org.smartut.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT();
    org.smartut.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.smartut.runtime.Runtime.getInstance().resetRuntime();
  } 

  @AfterClass 
  public static void clearSmartUtFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.smartut.runtime.jvm.ShutdownHookHandler.getInstance().initHandler();
    org.smartut.runtime.sandbox.Sandbox.goingToExecuteSUTCode();
    setSystemProperties(); 
    org.smartut.runtime.GuiSupport.setHeadless();
    org.smartut.runtime.Runtime.getInstance().resetRuntime();
    org.smartut.runtime.agent.InstrumentingAgent.activate();
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.smartut.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks();
    org.smartut.runtime.classhandling.JDKClassResetter.reset();
    resetClasses(); 
    org.smartut.runtime.sandbox.Sandbox.doneWithExecutingSUTCode();
    org.smartut.runtime.agent.InstrumentingAgent.deactivate();
    org.smartut.runtime.GuiSupport.restoreHeadlessMode();
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "/tmp"); 
    java.lang.System.setProperty("user.home", "/tmp/home/user"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "user"); 
    java.lang.System.setProperty("user.timezone", "Europe/Lisbon"); 
  }

  private static void initializeClasses() {
    org.smartut.runtime.classhandling.ClassStateSupport.initializeClasses(CharacterCounter_ESTest_scaffolding.class.getClassLoader() ,
      "org.ant_project_example.CharacterCounter"
    );
  } 

  private static void resetClasses() {
    org.smartut.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CharacterCounter_ESTest_scaffolding.class.getClassLoader());

    org.smartut.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.ant_project_example.CharacterCounter"
    );
  }
}
